title: Nonograph
author:
  name: Bruno Buglio
  email: 'bruno.buglio@gmail.com'
metadata:
    description: 'Bruno Buglio awesome portfolio'
taxonomies: [category,tag,CD,AD,account]


#personal vars
project_thumbnail: preview.jpg
